"""create game table

Revision ID: ef9245c8398f
Revises: 
Create Date: 2021-10-27 23:24:24.594420

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'ef9245c8398f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('winner', sa.String(length=1), nullable=True),
                    sa.Column('is_over', sa.Boolean(), nullable=True),
                    sa.Column('next_player', sa.String(length=1), nullable=True),
                    sa.Column('grid', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('ended_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game')
    # ### end Alembic commands ###
